name: poker_assistant
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  syncfusion_flutter_charts: 20.2.43
  charts_flutter: 0.12.0
  cupertino_icons: ^1.0.5
  dotted_border: ^2.0.0+2
  shared_preferences: ^2.0.15
  carousel_slider: ^4.1.1
  cube_transition_plus: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  dart_code_metrics: 4.17.0

flutter:
  fonts:
    - family: Bitter
      fonts:
        - asset: assets/Bitter-ExtraBold.ttf

  uses-material-design: true
flutter_intl:
  enabled: true
